FROM php:7.2-fpm-alpine

# Install dependencies
RUN apk update && apk upgrade && apk add --update \
    zip \
    unzip \
    bash \
    curl \
    procps \
    git \
    vim \
    zlib-dev \
    jpeg-dev \
    libpng-dev \
    nginx \
    nodejs \
    npm \
    mysql-client \
    httpie \
    python3 \
    py3-pip

# Install supervisord
RUN apk add --update supervisor
COPY supervisord/supervisord.conf /etc/supervisord.conf

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer --1

# Install yarn
RUN npm install -g yarn

# Install extensions
RUN docker-php-ext-install \
    pdo_mysql \
    mbstring \
    zip \
    exif \
    pcntl \
    gd

# Set the working directory to /var/www
RUN rm -rf /var/www \
    && mkdir -p /var/www \
    && chown -R www-data:www-data /var/www
WORKDIR /var/www

# Configure PHP
RUN rm -rf /usr/local/etc/php-fpm.d/*.conf
COPY php/php.ini /usr/local/etc/php/php.ini
COPY php/php-fpm.conf /usr/local/etc/php-fpm.conf
COPY php/php-fpm.d /usr/local/etc/php-fpm.d

# Configure nginx
RUN rm -rf /etc/nginx/conf.d/* \
    && mkdir -p /run/nginx
COPY nginx  /etc/nginx

STOPSIGNAL SIGTERM
EXPOSE 8080
CMD ["supervisord", "-n", "-c", "/etc/supervisord.conf"]
