name: Pull Requests

on:
  pull_request:
    branches:
      - '[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: |
          docker build -t bts/php:latest .
