name: Push

on:
  push:
    branches: [ main ]

jobs:
  version-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: set-matrix
        name: Determine version matrix
        run: |
          versions=($(find . -name "Dockerfile.*" | cut -d '.' -f3-))
          echo "matrix=$(jq --compact-output --null-input '$ARGS.positional' --args -- "${versions[@]}")" | tee -a $GITHUB_OUTPUT
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs:
      - version-matrix
    strategy:
      matrix:
        version: ${{ fromJson(needs.version-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - name: Set up builder
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      - name: Log into the registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          file: Dockerfile.${{ matrix.version }}
          tags: |
            ghcr.io/backstage-technical-services/php-docker:${{ matrix.version }}
